# Generated by Django 5.0.6 on 2025-08-27 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('wallet', models.CharField(max_length=255, unique=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('reputation_score', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('type', models.CharField(choices=[('ArtCraft', 'Art & Crafts'), ('Music', 'Music'), ('Fashion', 'Fashion'), ('Tourism', 'Tourism'), ('Heritage', 'Heritage'), ('Software', 'Software')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('physical', models.BooleanField(default=False)),
                ('digital', models.BooleanField(default=False)),
                ('digital_scan', models.BooleanField(default=False)),
                ('redeemable', models.BooleanField(default=False)),
                ('license_based', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImpactScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heritage_value', models.PositiveIntegerField(default=0)),
                ('sustainability_score', models.PositiveIntegerField(default=0)),
                ('sdg_alignment', models.JSONField(blank=True, default=list)),
                ('computed_value', models.PositiveIntegerField(blank=True, null=True)),
                ('nft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='core.nft')),
            ],
            options={
                'ordering': ['nft__code'],
            },
        ),
        migrations.CreateModel(
            name='FundingThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('nft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funding_threshold', to='core.nft')),
            ],
            options={
                'ordering': ['nft__code'],
            },
        ),
        migrations.CreateModel(
            name='DynamicOwnershipRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('transfer_rule', 'transfer_rule'), ('decay_rule', 'decay_rule')], max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_rules', to='core.nft')),
            ],
            options={
                'ordering': ['nft__code', 'rule_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NFTEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.nft')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NFTUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('provenance', 'provenance'), ('resale_rights', 'resale_rights'), ('streaming_rights', 'streaming_rights'), ('royalties', 'royalties'), ('redeem_physical', 'redeem_physical'), ('digital_wearable', 'digital_wearable'), ('redeemable_experience', 'redeemable_experience'), ('eco_tourism_support', 'eco_tourism_support'), ('archive_access', 'archive_access'), ('preservation_funding', 'preservation_funding'), ('license_key', 'license_key'), ('subscription_access', 'subscription_access'), ('royalty_share', 'royalty_share'), ('lifetime_access', 'lifetime_access'), ('in_game_assets', 'in_game_assets'), ('updates_access', 'updates_access')], max_length=64)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='core.nft')),
            ],
            options={
                'ordering': ['nft__code', 'utility_type'],
                'unique_together': {('nft', 'utility_type')},
            },
        ),
        migrations.AddField(
            model_name='nft',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='core.product'),
        ),
        migrations.CreateModel(
            name='UtilityGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255)),
                ('nft_utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='core.nftutility')),
            ],
            options={
                'ordering': ['nft_utility__nft__code', 'nft_utility__utility_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GovernanceVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('reputation_weighted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_votes', to='core.creator')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_votes', to='core.nft')),
            ],
            options={
                'ordering': ['nft__code', '-weight'],
                'unique_together': {('nft', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='core.creator')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='core.nft')),
            ],
            options={
                'ordering': ['nft__code', '-percentage'],
                'unique_together': {('nft', 'creator')},
            },
        ),
    ]
