# Generated by Django 5.2.5 on 2025-08-27 13:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('wallet_address', models.CharField(max_length=200, unique=True)),
                ('reputation_score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('type', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('physical', models.BooleanField(default=False)),
                ('digital', models.BooleanField(default=False)),
                ('digital_scan', models.BooleanField(default=False)),
                ('redeemable', models.BooleanField(default=False)),
                ('license_based', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SDGTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundingThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('nft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funding_threshold', to='core.nft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DynamicOwnershipRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('transfer_rule', 'Transfer Rule'), ('decay_rule', 'Decay Rule')], max_length=32)),
                ('rule_text', models.TextField()),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.creator')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_rules', to='core.nft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NFTActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=200)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.nft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='nft',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='core.product'),
        ),
        migrations.CreateModel(
            name='ImpactScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heritage_value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sustainability_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='core.nft')),
                ('sdg_alignment', models.ManyToManyField(blank=True, related_name='impacts', to='core.sdgtag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='creator',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='creators', to='core.skill'),
        ),
        migrations.AddField(
            model_name='nft',
            name='utilities',
            field=models.ManyToManyField(blank=True, related_name='nfts', to='core.utility'),
        ),
        migrations.CreateModel(
            name='GovernanceVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('reputation_weighted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_votes', to='core.creator')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_votes', to='core.nft')),
            ],
            options={
                'unique_together': {('nft', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='NFTOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='core.creator')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='core.nft')),
            ],
            options={
                'unique_together': {('nft', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='UtilityGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.CharField(max_length=200)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_gates', to='core.nft')),
                ('utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='core.utility')),
            ],
            options={
                'unique_together': {('nft', 'utility', 'condition')},
            },
        ),
    ]
