# Generated by Django 5.2.5 on 2025-08-27 13:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('contract_address', models.CharField(blank=True, max_length=100)),
                ('metadata_uri', models.URLField(blank=True)),
                ('funding_threshold', models.DecimalField(decimal_places=2, help_text='Funding threshold in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_funding', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('heritage_value', models.IntegerField(default=50, help_text='Heritage value score from 0 to 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sustainability_score', models.IntegerField(default=50, help_text='Sustainability score from 0 to 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sdg_alignment', models.JSONField(default=list, help_text='List of aligned Sustainable Development Goals')),
                ('history', models.JSONField(default=list, help_text='Transaction and event history')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GovernanceVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Vote weight (0 to 1)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('is_reputation_weighted', models.BooleanField(default=True, help_text='Whether vote weight is adjusted by creator reputation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_votes', to='creators.creator')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_votes', to='nfts.nft')),
            ],
            options={
                'unique_together': {('nft', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Ownership percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('transfer_rule', models.TextField(blank=True, help_text='Rule for ownership transfer')),
                ('decay_rule', models.TextField(blank=True, help_text='Rule for ownership decay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_ownerships', to='creators.creator')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='nfts.nft')),
            ],
            options={
                'ordering': ['-percentage'],
                'unique_together': {('nft', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('provenance', 'Provenance'), ('resale_rights', 'Resale Rights'), ('streaming_rights', 'Streaming Rights'), ('royalties', 'Royalties'), ('redeem_physical', 'Redeem Physical Item'), ('digital_wearable', 'Digital Wearable'), ('redeemable_experience', 'Redeemable Experience'), ('eco_tourism_support', 'Eco Tourism Support'), ('archive_access', 'Archive Access'), ('preservation_funding', 'Preservation Funding'), ('license_key', 'License Key'), ('subscription_access', 'Subscription Access'), ('royalty_share', 'Royalty Share'), ('lifetime_access', 'Lifetime Access'), ('in_game_assets', 'In-Game Assets'), ('updates_access', 'Updates Access')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ownership_requirement', models.DecimalField(decimal_places=2, default=0, help_text='Minimum ownership percentage required to access this utility', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('condition', models.CharField(blank=True, help_text='Additional condition for accessing this utility', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='nfts.nft')),
            ],
            options={
                'verbose_name_plural': 'Utilities',
                'unique_together': {('nft', 'utility_type')},
            },
        ),
    ]
