# Generated by Django 5.2.5 on 2025-08-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('ArtCraft', 'Art & Craft'), ('Music', 'Music'), ('Fashion', 'Fashion'), ('Tourism', 'Tourism'), ('Heritage', 'Heritage'), ('Software', 'Software')], max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Beadwork', 'Beadwork'), ('Painting', 'Painting'), ('Sculpture', 'Sculpture'), ('Afrobeat', 'Afrobeat'), ('Traditional', 'Traditional'), ('Contemporary', 'Contemporary'), ('Textile', 'Textile'), ('Jewelry', 'Jewelry'), ('Accessories', 'Accessories'), ('AI/ML', 'AI/ML'), ('Gaming', 'Gaming'), ('Tools', 'Tools'), ('Other', 'Other')], max_length=50)),
                ('is_physical', models.BooleanField(default=False)),
                ('is_digital', models.BooleanField(default=True)),
                ('has_digital_scan', models.BooleanField(default=False)),
                ('is_redeemable', models.BooleanField(default=False)),
                ('is_license_based', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('digital_file', models.FileField(blank=True, null=True, upload_to='products/files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
