# Generated by Django 5.2.5 on 2025-08-27 13:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0001_initial'),
        ('nfts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_creators', models.IntegerField(default=0)),
                ('verified_creators', models.IntegerField(default=0)),
                ('average_reputation', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_nfts', models.IntegerField(default=0)),
                ('funded_nfts', models.IntegerField(default=0)),
                ('total_funding_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_products', models.IntegerField(default=0)),
                ('products_by_type', models.JSONField(default=dict)),
                ('daily_transactions', models.IntegerField(default=0)),
                ('daily_volume', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_heritage_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_sustainability_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ImpactMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heritage_value', models.IntegerField()),
                ('sustainability_score', models.IntegerField()),
                ('overall_impact_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_supporters', models.IntegerField(default=0)),
                ('total_funding', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transactions_count', models.IntegerField(default=0)),
                ('utilities_redeemed', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_metrics', to='nfts.nft')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('mint', 'Mint'), ('transfer', 'Transfer'), ('sale', 'Sale'), ('funding', 'Funding Contribution'), ('utility_redemption', 'Utility Redemption')], max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Ownership percentage transferred', max_digits=5, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=100)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_sent', to='creators.creator')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='nfts.nft')),
                ('to_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_received', to='creators.creator')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
