# Generated by Django 5.2.5 on 2025-08-27 13:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_nfts', models.IntegerField(default=0)),
                ('total_creators', models.IntegerField(default=0)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active_listings', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Marketplace Statistics',
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=255, unique=True)),
                ('skills', models.JSONField(default=list)),
                ('reputation_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reputation_score'],
            },
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_id', models.CharField(max_length=255, unique=True)),
                ('metadata_uri', models.URLField(blank=True)),
                ('blockchain', models.CharField(default='Ethereum', max_length=50)),
                ('contract_address', models.CharField(blank=True, max_length=255)),
                ('is_minted', models.BooleanField(default=False)),
                ('is_listed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='marketplace.creator')),
            ],
        ),
        migrations.CreateModel(
            name='ImpactScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heritage_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sustainability_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sdg_alignment', models.JSONField(default=list)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('nft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_score', to='marketplace.nft')),
            ],
        ),
        migrations.CreateModel(
            name='GovernanceVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('is_reputation_weighted', models.BooleanField(default=True)),
                ('vote_timestamp', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_votes', to='marketplace.creator')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_votes', to='marketplace.nft')),
            ],
        ),
        migrations.CreateModel(
            name='FundingThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funding_threshold', to='marketplace.nft')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(max_length=50)),
                ('rule_description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_ownership_rules', to='marketplace.nft')),
            ],
        ),
        migrations.CreateModel(
            name='NFTHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('mint', 'Mint'), ('sale', 'Sale'), ('transfer', 'Transfer'), ('upgrade', 'Upgrade'), ('stream', 'Stream'), ('redeem', 'Redeem'), ('vote', 'Vote')], max_length=20)),
                ('action_description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='marketplace.nft')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('ArtCraft', 'Art & Craft'), ('Music', 'Music'), ('Fashion', 'Fashion'), ('Tourism', 'Tourism'), ('Heritage', 'Heritage'), ('Software', 'Software')], max_length=50)),
                ('category', models.CharField(blank=True, choices=[('Beadwork', 'Beadwork'), ('Afrobeat', 'Afrobeat'), ('Textile', 'Textile'), ('AI/ML', 'AI/ML'), ('Gaming', 'Gaming'), ('EcoTourism', 'Eco Tourism'), ('OralHistory', 'Oral History')], max_length=50)),
                ('description', models.TextField()),
                ('is_physical', models.BooleanField(default=False)),
                ('is_digital', models.BooleanField(default=False)),
                ('is_redeemable', models.BooleanField(default=False)),
                ('has_digital_scan', models.BooleanField(default=False)),
                ('is_license_based', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.creator')),
            ],
        ),
        migrations.AddField(
            model_name='nft',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nft', to='marketplace.product'),
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('provenance', 'Provenance'), ('resale_rights', 'Resale Rights'), ('streaming_rights', 'Streaming Rights'), ('royalties', 'Royalties'), ('redeem_physical', 'Redeem Physical'), ('digital_wearable', 'Digital Wearable'), ('redeemable_experience', 'Redeemable Experience'), ('eco_tourism_support', 'Eco Tourism Support'), ('archive_access', 'Archive Access'), ('preservation_funding', 'Preservation Funding'), ('license_key', 'License Key'), ('subscription_access', 'Subscription Access'), ('royalty_share', 'Royalty Share'), ('lifetime_access', 'Lifetime Access'), ('in_game_assets', 'In-Game Assets'), ('updates_access', 'Updates Access')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='marketplace.nft')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_gates', to='marketplace.nft')),
                ('utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='marketplace.utility')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='marketplace.creator')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='marketplace.nft')),
            ],
            options={
                'unique_together': {('nft', 'creator')},
            },
        ),
    ]
